[package]
name = "rume"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"

[lib]
crate-type = ["staticlib"]
name = "rume"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
