use std::fmt::Display;

pub enum RumeKeyTable {
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Backspace,
    Backtick,
    Colon,
    Comma,
    DoubleQuote,
    Enter,
    Equal,
    Escape,
    ExclamationMarkDown,
    ExclamationMarkUp,
    LetterA,
    LetterB,
    LetterC,
    LetterD,
    LetterE,
    LetterF,
    LetterG,
    LetterH,
    LetterI,
    LetterJ,
    LetterK,
    LetterL,
    LetterM,
    LetterN,
    LetterO,
    LetterP,
    LetterQ,
    LetterR,
    LetterS,
    LetterT,
    LetterU,
    LetterV,
    LetterW,
    LetterX,
    LetterY,
    LetterZ,
    Minus,
    Period,
    Plus,
    QuestionMarkDown,
    QuestionMarkUp,
    Semicolon,
    SingleQuote,
    SlashBackward,
    SlashForward,
    Space,
    Tilde,
    Underscore,
}

impl Display for RumeKeyTable {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RumeKeyTable::ArrowDown => write!(f, "ArrowDown"),
            RumeKeyTable::ArrowLeft => write!(f, "ArrowLeft"),
            RumeKeyTable::ArrowRight => write!(f, "ArrowRight"),
            RumeKeyTable::ArrowUp => write!(f, "ArrowUp"),
            RumeKeyTable::Backspace => write!(f, "Backspace"),
            RumeKeyTable::Backtick => write!(f, "`"),
            RumeKeyTable::Colon => write!(f, ":"),
            RumeKeyTable::Comma => write!(f, ","),
            RumeKeyTable::DoubleQuote => write!(f, "\""),
            RumeKeyTable::Enter => write!(f, "Enter"),
            RumeKeyTable::Equal => write!(f, "="),
            RumeKeyTable::Escape => write!(f, "Escape"),
            RumeKeyTable::ExclamationMarkDown => write!(f, "!"),
            RumeKeyTable::ExclamationMarkUp => write!(f, "¡"),
            RumeKeyTable::LetterA => write!(f, "a"),
            RumeKeyTable::LetterB => write!(f, "b"),
            RumeKeyTable::LetterC => write!(f, "c"),
            RumeKeyTable::LetterD => write!(f, "d"),
            RumeKeyTable::LetterE => write!(f, "e"),
            RumeKeyTable::LetterF => write!(f, "f"),
            RumeKeyTable::LetterG => write!(f, "g"),
            RumeKeyTable::LetterH => write!(f, "h"),
            RumeKeyTable::LetterI => write!(f, "i"),
            RumeKeyTable::LetterJ => write!(f, "j"),
            RumeKeyTable::LetterK => write!(f, "k"),
            RumeKeyTable::LetterL => write!(f, "l"),
            RumeKeyTable::LetterM => write!(f, "m"),
            RumeKeyTable::LetterN => write!(f, "n"),
            RumeKeyTable::LetterO => write!(f, "o"),
            RumeKeyTable::LetterP => write!(f, "p"),
            RumeKeyTable::LetterQ => write!(f, "q"),
            RumeKeyTable::LetterR => write!(f, "r"),
            RumeKeyTable::LetterS => write!(f, "s"),
            RumeKeyTable::LetterT => write!(f, "t"),
            RumeKeyTable::LetterU => write!(f, "u"),
            RumeKeyTable::LetterV => write!(f, "v"),
            RumeKeyTable::LetterW => write!(f, "w"),
            RumeKeyTable::LetterX => write!(f, "x"),
            RumeKeyTable::LetterY => write!(f, "y"),
            RumeKeyTable::LetterZ => write!(f, "z"),
            RumeKeyTable::Minus => write!(f, "-"),
            RumeKeyTable::Period => write!(f, "."),
            RumeKeyTable::Plus => write!(f, "+"),
            RumeKeyTable::QuestionMarkDown => write!(f, "?"),
            RumeKeyTable::QuestionMarkUp => write!(f, "¿"),
            RumeKeyTable::Semicolon => write!(f, ";"),
            RumeKeyTable::SingleQuote => write!(f, "'"),
            RumeKeyTable::SlashBackward => write!(f, "\\"),
            RumeKeyTable::SlashForward => write!(f, "/"),
            RumeKeyTable::Space => write!(f, " "),
            RumeKeyTable::Tilde => write!(f, "~"),
            RumeKeyTable::Underscore => write!(f, "_"),
        }
    }
}
